import type { Metadata } from "next";
import "../scss/main.scss";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <div className="site">
          <Header />
          {children}
          {/*<MobileBar/>*/}
          <Footer />
        </div>
      </body>
    </html>
  );
}
